### ISSUE TITLE
My website link doesn't work.

### ISSUE THREAD

**Issue by npgockel** [Mleuer/Color-Story#147]
I clicked on my website link from my post and it sent me to https://color-story.herokuapp.com/squaddle.in instead of Squadle

Project-KAPF FTW!!!

**Comment by CrainDavis** [comment]
You need to put the **full** URL in (include the "https://" at the front), otherwise you will run into that problem. There should have been text that stated this. I'll try and see if I can improve this aspect though.

**Comment by CrainDavis** [comment]
Ok, I have resolved the issue!!
